/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

import Datos.LecturaDatos;
import Logica.Metodos;
import java.io.*;
import java.util.*;
import javax.swing.*;
import java.io.IOException;

/**
 *
 * @author anon
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    LecturaDatos le = new LecturaDatos();
    Metodos pro = new Metodos();
    public String cap[] = new String[8];
    String concat;

    public Principal() {
        initComponents();
        this.setResizable(false);
        this.setLocation(300, 100);
        setSize(630, 620);
          jLabel4.setIcon(icono = new ImageIcon("C://users//anon//Documents//NetBeansProjects/PROYECTOFINAL//imagenes LEON//inicio.jpg"));

          Pista.setIcon(icono = new ImageIcon("C://users//anon//Documents//NetBeansProjects/PROYECTOFINAL//imagenes LEON//s.png"));

    }
    int pasar = 0;
    ImageIcon icono = null;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        digito4 = new javax.swing.JTextField();
        Pista = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        digito3 = new javax.swing.JTextField();
        digito2 = new javax.swing.JTextField();
        digito1 = new javax.swing.JTextField();
        digito5 = new javax.swing.JTextField();
        digito6 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Adivina el personaje");

        jButton1.setText("Generar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        digito4.setBackground(new java.awt.Color(255, 255, 0));
        digito4.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(51, 51, 51)));
        digito4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                digito4ActionPerformed(evt);
            }
        });
        digito4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                digito4KeyReleased(evt);
            }
        });

        Pista.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 51, 51)));

        jLabel4.setBorder(new javax.swing.border.MatteBorder(null));

        digito3.setBackground(new java.awt.Color(255, 255, 0));
        digito3.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(51, 51, 51)));
        digito3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                digito3ActionPerformed(evt);
            }
        });
        digito3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                digito3KeyReleased(evt);
            }
        });

        digito2.setBackground(new java.awt.Color(255, 255, 0));
        digito2.setBorder(new javax.swing.border.MatteBorder(null));
        digito2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                digito2ActionPerformed(evt);
            }
        });
        digito2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                digito2KeyReleased(evt);
            }
        });

        digito1.setBackground(new java.awt.Color(255, 255, 0));
        digito1.setBorder(new javax.swing.border.MatteBorder(null));
        digito1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                digito1ActionPerformed(evt);
            }
        });
        digito1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                digito1KeyReleased(evt);
            }
        });

        digito5.setBackground(new java.awt.Color(255, 255, 0));
        digito5.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(51, 51, 51)));
        digito5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                digito5ActionPerformed(evt);
            }
        });
        digito5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                digito5KeyReleased(evt);
            }
        });

        digito6.setBackground(new java.awt.Color(255, 255, 0));
        digito6.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(51, 51, 51)));
        digito6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                digito6ActionPerformed(evt);
            }
        });
        digito6.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                digito6KeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(77, 77, 77)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(digito1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(digito2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(digito3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(digito4, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(digito5, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(digito6, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(126, 126, 126))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(146, 146, 146))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(Pista, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(76, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(digito2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(digito1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(digito3, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(digito4, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(digito5, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(digito6, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(Pista, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void digito6KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_digito6KeyReleased

        int a = digito6.getText().length();
        if (a >= 2) {
            digito6.setText(digito6.getText().substring(0,1));
        }// TODO add your handling code here:
    }//GEN-LAST:event_digito6KeyReleased

    private void digito6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_digito6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_digito6ActionPerformed

    private void digito5KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_digito5KeyReleased
        int a = digito5.getText().length();
        if (a >= 2) {
            digito5.setText(digito5.getText().substring(0,1));
        } // TODO add your handling code here:
    }//GEN-LAST:event_digito5KeyReleased

    private void digito5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_digito5ActionPerformed

        // TODO add your handling code here:
    }//GEN-LAST:event_digito5ActionPerformed

    private void digito1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_digito1KeyReleased
        int a = digito1.getText().length();
        if (a >= 2) {
            digito1.setText(digito1.getText().substring(0,1));
        }// TODO add your handling code here:
    }//GEN-LAST:event_digito1KeyReleased

    private void digito1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_digito1ActionPerformed

        // TODO add your handling code here:
    }//GEN-LAST:event_digito1ActionPerformed

    private void digito2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_digito2KeyReleased
        int a = digito2.getText().length();
        if (a >= 2) {
            digito2.setText(digito2.getText().substring(0,1));
        } // TODO add your handling code here:
    }//GEN-LAST:event_digito2KeyReleased

    private void digito2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_digito2ActionPerformed

        // TODO add your handling code here:
    }//GEN-LAST:event_digito2ActionPerformed

    private void digito3KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_digito3KeyReleased
        int a = digito3.getText().length();
        if (a >= 2) {
            digito3.setText(digito3.getText().substring(0,1));
        }// TODO add your handling code here:
    }//GEN-LAST:event_digito3KeyReleased

    private void digito3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_digito3ActionPerformed

        // TODO add your handling code here:
    }//GEN-LAST:event_digito3ActionPerformed

    private void digito4KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_digito4KeyReleased
        int a = digito4.getText().length();
        if (a >= 2) {
            digito4.setText(digito4.getText().substring(0,1));
        } // TODO add your handling code here:
    }//GEN-LAST:event_digito4KeyReleased

    private void digito4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_digito4ActionPerformed

        // TODO add your handling code here:
    }//GEN-LAST:event_digito4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            le.lectura();
            if (pasar <= 1) {
                jButton1.setText("validar respuesta");
                Pista.setText(le.datoleido[0]);
                pasar = 2;
            } else  {
                concat();
                if (concat.equals(le.datoleido[1])) {
                    JOptionPane.showMessageDialog(null, "Felicidades has ganado");

                    limpiar();
                } else {
                    rtausuario();
                    pro.rtausuario(cap);
                    correccion();
                    cambioimagen();
                }

            }

        } catch (IOException ex) {
            System.out.println("error");
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    public void rtausuario() {
        cap[0] = digito1.getText();
        cap[1] = digito2.getText();
        cap[2] = digito3.getText();
        cap[3] = digito4.getText();
        cap[4] = digito5.getText();
        cap[5] = digito6.getText();

    }

    public void correccion() {
        digito1.setText(pro.comparado[0]);
        digito2.setText(pro.comparado[1]);
        digito3.setText(pro.comparado[2]);
        digito4.setText(pro.comparado[3]);
        digito5.setText(pro.comparado[4]);
        digito6.setText(pro.comparado[5]);

    }

    public void concat() {
        concat = digito1.getText() + digito2.getText() + digito3.getText() + digito4.getText() + digito5.getText()+digito6.getText();

    }

    public void cambioimagen() {
        if (pasar == 2) {
            icono = new ImageIcon("C://users//anon//Documents//NetBeansProjects/PROYECTOFINAL//imagenes LEON//segundo.jpg");
        } else if (pasar == 3) {
            icono = new ImageIcon("C://users//anon//Documents//NetBeansProjects/PROYECTOFINAL//imagenes LEON//tercero.jpg");
        } else if (pasar == 4) {
            icono = new ImageIcon("C://users//anon//Documents//NetBeansProjects/PROYECTOFINAL//imagenes LEON//cuarto.jpg");
        } else if (pasar == 5) {
            icono = new ImageIcon("C://users//anon//Documents//NetBeansProjects/PROYECTOFINAL//imagenes LEON//quinto.jpg");
        } else if (pasar == 6) {
            icono = new ImageIcon("C://users//anon//Documents//NetBeansProjects/PROYECTOFINAL//imagenes LEON//sexto.jpg");
        } else if (pasar == 7) {
            icono = new ImageIcon("C://users//anon//Documents//NetBeansProjects/PROYECTOFINAL//imagenes LEON//septimo.jpg");
        } else if (pasar == 8) {
            icono = new ImageIcon("C://users//anon//Documents//NetBeansProjects/PROYECTOFINAL//imagenes LEON//octavo.jpg");
        } if  (pasar == 8) {
            jLabel4.setIcon(icono);
            JOptionPane.showMessageDialog(null, "lo siento perdiste ");
        limpiar();
        }else {
            jLabel4.setIcon(icono);
            pasar=pasar+1;
        }
       
        
    }
    
public void limpiar(){
    digito1.setText("");
    digito2.setText("");
    digito3.setText("");
    digito4.setText("");
    digito5.setText("");
    digito6.setText("");
    Pista.setText("");
    pasar=1;
    jButton1.setText("iniciar");
    jLabel4.setIcon(icono=new ImageIcon("C://users//anon//Documents//NetBeansProjects/PROYECTOFINAL//imagenes LEON//inicio.jpg"));
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Pista;
    private javax.swing.JTextField digito1;
    private javax.swing.JTextField digito2;
    private javax.swing.JTextField digito3;
    private javax.swing.JTextField digito4;
    private javax.swing.JTextField digito5;
    private javax.swing.JTextField digito6;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
